-- MySQL Script generated by MySQL Workbench
-- 10/15/15 21:33:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema raziel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(200) NOT NULL,
  `password` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `last_login_at` DATETIME NULL,
  `deleted` DATETIME NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `login_UNIQUE` ON `user` (`login` ASC, `deleted` ASC);


-- -----------------------------------------------------
-- Table `secret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secret` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `secret` MEDIUMBLOB NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `created_by` SMALLINT UNSIGNED NOT NULL,
  `updated_by` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_secret_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_secret_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `slug_UNIQUE` ON `secret` (`slug` ASC);

CREATE INDEX `fk_secret_user1_idx` ON `secret` (`created_by` ASC);

CREATE INDEX `fk_secret_user2_idx` ON `secret` (`updated_by` ASC);


-- -----------------------------------------------------
-- Table `consumer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `info_token` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `created_by` SMALLINT UNSIGNED NOT NULL,
  `updated_by` SMALLINT UNSIGNED NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_consumer_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consumer_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_consumer_user1_idx` ON `consumer` (`created_by` ASC);

CREATE INDEX `fk_consumer_user2_idx` ON `consumer` (`updated_by` ASC);


-- -----------------------------------------------------
-- Table `access_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `access_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `secret_id` INT UNSIGNED NULL,
  `consumer_id` INT UNSIGNED NULL,
  `requested_at` DATETIME NOT NULL,
  `origin_ip` VARCHAR(45) NOT NULL,
  `status` SMALLINT UNSIGNED NOT NULL,
  `context` MEDIUMBLOB NULL,
  `request_body` MEDIUMBLOB NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_access_log_secret1`
    FOREIGN KEY (`secret_id`)
    REFERENCES `secret` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_access_log_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `consumer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_access_log_secret1_idx` ON `access_log` (`secret_id` ASC);

CREATE INDEX `fk_access_log_consumer1_idx` ON `access_log` (`consumer_id` ASC);


-- -----------------------------------------------------
-- Table `consumer_secret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumer_secret` (
  `consumer_id` INT UNSIGNED NOT NULL,
  `secret_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`consumer_id`, `secret_id`),
  CONSTRAINT `fk_consumer_secret_secret1`
    FOREIGN KEY (`secret_id`)
    REFERENCES `secret` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consumer_secret_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `consumer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_consumer_secret_secret1_idx` ON `consumer_secret` (`secret_id` ASC);


-- -----------------------------------------------------
-- Table `audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `secret_id` INT UNSIGNED NULL,
  `consumer_id` INT UNSIGNED NULL,
  `user_id` SMALLINT UNSIGNED NULL,
  `action` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `created_by` SMALLINT UNSIGNED NOT NULL,
  `origin_ip` VARCHAR(45) NOT NULL,
  `user_agent` VARCHAR(255) NULL,
  `context` TEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_audit_log_secret0`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `consumer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_log_user10`
    FOREIGN KEY (`created_by`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_log_secret`
    FOREIGN KEY (`secret_id`)
    REFERENCES `secret` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_log_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_audit_log_user1_idx` ON `audit_log` (`created_by` ASC);

CREATE INDEX `fk_audit_log_secret0_idx` ON `audit_log` (`consumer_id` ASC);

CREATE INDEX `fk_audit_log_secret_idx` ON `audit_log` (`secret_id` ASC);

CREATE INDEX `fk_audit_log_user_idx` ON `audit_log` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `restriction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restriction` (
  `consumer_id` INT UNSIGNED NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `context` MEDIUMBLOB NULL,
  PRIMARY KEY (`consumer_id`, `type`),
  CONSTRAINT `fk_restriction_consumer1`
    FOREIGN KEY (`consumer_id`)
    REFERENCES `consumer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_restriction_consumer1_idx` ON `restriction` (`consumer_id` ASC);


-- -----------------------------------------------------
-- Table `config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `config` (
  `key` VARCHAR(30) NOT NULL,
  `value` BLOB NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `config`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `config` (`key`, `value`) VALUES ('teststring', NULL);
INSERT INTO `config` (`key`, `value`) VALUES ('version', 0x312E30);

COMMIT;

